### ISSUE TITLE
Sonderangebote - per ID hinzufügen - Fatal error

### ISSUE THREAD

**Issue by webchills** [zencartpro/zencart-german-grundsystem#11]
using PHP 8 and only if using MySQL in strict mode

`Request URI: /admin/index.php?cmd=specials&action=pre_add
--> PHP Fatal error: Uncaught TypeError: Unsupported operand types: string + int in admin/includes/functions/general.php:2259
Stack trace:
#0 /admin/specials.php(543): zen_set_field_length()
#1 /admin/index.php(18): require('...')
#2 {main}
thrown in /admin/includes/functions/general.php on line 2259.`

**Comment by webchills** [comment]
fixed with d3367e0
