### ISSUE TITLE
PHP Fatal error: Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#25]
Ich erhalte mehrere PHP Fehler angezeigt. U.a. verschiedene Fatal error:
PHP: 8.0.29
zc 1.5.7f

```
[03-Jul-2023 11:45:36 Europe/Berlin] PHP Fatal error: Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given in /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php:105
Stack trace:
#0 /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php(105): str_repeat()
#1 /includes/templates/responsive_classic/templates/tpl_featured_products_default.php(89): require('...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(179): require('...')
#3 /index.php(95): require('...')
#4 {main}
thrown in /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php on line 105

[03-Jul-2023 11:45:36 Europe/Berlin] Request URI: /index.php?main_page=featured_products&page=2, IP address: 66.249.66.162
--> PHP Fatal error: Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given in /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php:105
Stack trace:
#0 /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php(105): str_repeat()
#1 /includes/templates/responsive_classic/templates/tpl_featured_products_default.php(89): require('...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(179): require('...')
#3 /index.php(95): require('...')
#4 {main}
thrown in /includes/templates/responsive_classic/templates/tpl_modules_products_featured_listing.php on line 105.
```

```
[03-Jul-2023 00:15:30 Europe/Berlin] PHP Fatal error: Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given in /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php:105
Stack trace:
#0 /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php(105): str_repeat()
#1 /includes/templates/responsive_classic/templates/tpl_products_all_default.php(80): require('...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(179): require('...')
#3 /index.php(95): require('...')
#4 {main}
thrown in /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php on line 105

[03-Jul-2023 00:15:30 Europe/Berlin] Request URI: /index.php?main_page=products_all&page=19, IP address: 216.244.66.239
--> PHP Fatal error: Uncaught TypeError: str_repeat(): Argument #2 ($times) must be of type int, string given in /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php:105
Stack trace:
#0 /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php(105): str_repeat()
#1 /includes/templates/responsive_classic/templates/tpl_products_all_default.php(80): require('...')
#2 /includes/templates/responsive_classic/common/tpl_main_page.php(179): require('...')
#3 /index.php(95): require('...')
#4 {main}
thrown in /includes/templates/responsive_classic/templates/tpl_modules_products_all_listing.php on line 105.
```

**Comment by webchills** [comment]
Prüfe folgende Einstellungen:
Konfiguration > Liste Alle Artikel > Jetzt Kaufen Button anzeigen
Konfiguration > Liste Empfohlene Artikel > Jetzt Kaufen Button anzeigen
Was ist dort eingestellt?

**Comment by webconcept-one** [comment]
Da habe ich ich "0" eingestellt.

**Comment by webchills** [comment]
Ändere das jeweils auf 0000, dann wird es OK sein

**Comment by webconcept-one** [comment]
Danke,
ich werds beobachten.
