### ISSUE TITLE
157F -> 157G: unvollständige Darstellung Admin Kategorien

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#29]
ich habe das Upgrade in einem Testshop durchgeführt.
Dabei habe ich ein Problem festgestellt.
In der Kategorieansicht wird nur eine Kategorie (bzw. Unterkategorie; bzw ein Artikel einer Kategorie) angezeigt.

![2023-12-16-151420_1920x1080_scrot](https://github.com/zencartpro/zencart-german-grundsystem/assets/23481663/4f0645a4-a207-469f-a20e-909939f48d21)

Bei mir fehlt auch der Footer in dieser Kategorieansicht.
Möglicherweise ist eines für diesen Bereich zuständigen Template Files (nur bei mir?) korrupt.

Ich habe alles nach Anleitung durchgeführt. Es gab keine Fehler.
Ich sehe es mir in den kommenden Tagen noch einmal an.
Außer jetzt aber alles noch einmal stupide (weil keine Fehler angezeigt wurden) zu wiederholen wüsste ich erst einmal nicht, was falsch gelaufen sein könnte.

**Comment by webchills** [comment]
Bei einer solchen Darstellung (Seite wird unvollständig geladen) muss es ein Logfile geben, das den Grund dafür anzeigt

**Comment by webconcept-one** [comment]
Ja gibt es:

```
[16-Dec-2023 15:13:43 Europe/Berlin] PHP Fatal error: Uncaught Error: Call to undefined function zen_get_category_metatag_fields() in /ADMIN/category_product_listing.php:769
Stack trace:
#0 /ADMIN/index.php(18): require()
#1 {main}
thrown in /ADMIN/category_product_listing.php on line 769

[16-Dec-2023 15:13:43 Europe/Berlin] Request URI: /ADMIN/index.php?cmd=category_product_listing, IP address: 2a02:8108:94c0:27a0:2cd2:9c0:7d8a:32de
--> PHP Fatal error: Uncaught Error: Call to undefined function zen_get_category_metatag_fields() in /ADMIN/category_product_listing.php:769
Stack trace:
#0 /ADMIN/index.php(18): require()
#1 {main}
thrown in /ADMIN/category_product_listing.php on line 769.

[16-Dec-2023 15:13:43 Europe/Berlin] Request URI: /ADMIN/index.php?cmd=category_product_listing, IP address: 2a02:8108:94c0:27a0:2cd2:9c0:7d8a:32de
--> PHP Fatal error: Uncaught Error: Call to undefined function zen_get_category_metatag_fields() in /ADMIN/category_product_listing.php:769
Stack trace:
#0 /ADMIN/index.php(18): require()
#1 {main}
thrown in /ADMIN/category_product_listing.php on line 769.
```
Zeile 769 lautet:
`if (zen_get_category_metatag_fields($category['categories_id'], (int)$_SESSION['languages_id'], 'metatags_keywords') || zen_get_category_metatag_fields($category['categories_id'], (int)$_SESSION['languages_id'], 'metatags_description')) { ?>`

**Comment by webchills** [comment]
Diese Funktion ist in der DEINADMIN/includes/functions/functions_metatags.php hinterlegt.
Diese Datei wurde anscheinend nicht hochgeladen

**Comment by webconcept-one** [comment]
Diese Datei ist aus einer vorherigen Installation vorhanden.

```
<?php
/**
 * metatags retrieval functions for admin
 *
 
 * @copyright Copyright 2003-2022 Zen Cart Development Team
 * Zen Cart German Version - www.zen-cart-pro.at
 * @license https://www.zen-cart-pro.at/license/3_0.txt GNU General Public License V3.0
 * @version $Id: functions_metatags.php 2021-10-25 17:49:16Z webchills $
 * @no-docs
 */

/**
 * product-specific meta tags
 */
  function zen_get_metatags_title($product_id, $language_id) {
    global $db;
    $product = $db->Execute("select metatags_title
                             from " . TABLE_META_TAGS_PRODUCTS_DESCRIPTION . "
                             where products_id = '" . (int)$product_id . "'
                             and language_id = '" . (int)$language_id . "'");
    if ($product->EOF) return '';
    return $product->fields['metatags_title'];
  }

  function zen_get_metatags_keywords($product_id, $language_id) {
    global $db;
    $product = $db->Execute("select metatags_keywords
                             from " . TABLE_META_TAGS_PRODUCTS_DESCRIPTION . "
                             where products_id = '" . (int)$product_id . "'
                             and language_id = '" . (int)$language_id . "'");
    if ($product->EOF) return '';
    return $product->fields['metatags_keywords'];
  }

  function zen_get_metatags_description($product_id, $language_id) {
    global $db;
    $product = $db->Execute("select metatags_description
                             from " . TABLE_META_TAGS_PRODUCTS_DESCRIPTION . "
                             where products_id = '" . (int)$product_id . "'
                             and language_id = '" . (int)$language_id . "'");
    if ($product->EOF) return '';
    return $product->fields['metatags_description'];
  }

/**
 * Category-specific metatags
 */
  function zen_get_category_metatags_title($category_id, $language_id) {
    global $db;
    $category = $db->Execute("select metatags_title
                              from " . TABLE_METATAGS_CATEGORIES_DESCRIPTION . "
                              where categories_id = '" . (int)$category_id . "'
                              and language_id = '" . (int)$language_id . "'");
    if ($category->EOF) return '';
    return $category->fields['metatags_title'];
  }

  function zen_get_category_metatags_description($category_id, $language_id) {
    global $db;
    $category = $db->Execute("select metatags_description
                              from " . TABLE_METATAGS_CATEGORIES_DESCRIPTION . "
                              where categories_id = '" . (int)$category_id . "'
                              and language_id = '" . (int)$language_id . "'");
    if ($category->EOF) return '';
    return $category->fields['metatags_description'];
  }

  function zen_get_category_metatags_keywords($category_id, $language_id) {
    global $db;
    $category = $db->Execute("select metatags_keywords
                              from " . TABLE_METATAGS_CATEGORIES_DESCRIPTION . "
                              where categories_id = '" . (int)$category_id . "'
                              and language_id = '" . (int)$language_id . "'");
    if ($category->EOF) return '';
    return $category->fields['metatags_keywords'];
  }
```

**Comment by webchills** [comment]
Ersetze sie mit der aus dem normalen 1.5.7g Download. Im Updatepaket fehlt der Hinweis, dass auch diese Datei geändert wurde, wird im Updatepaket entsprechend ersetzt werden.

**Comment by webconcept-one** [comment]
Danke!

**Comment by webchills** [comment]
fixed with dbf4c0c51c647f76bce2eb3c9d39e293d4897f89
