### ISSUE TITLE
Auswahl Coupon in Liste "Aktive Aktionscoupons" springt zu Liste "Alle Aktionscoupons"

### ISSUE THREAD

**Issue by webconcept-one** [zencartpro/zencart-german-grundsystem#48]
Ist die Anzeige "Aktive Aktionscoupons" ausgewählt und wird ein anderer Coupon als der erste zur Auswahl angeklickt, dann springt die Auswahl um auf "Alle Aktionscoupons".
Nur dann kann ein beliebiger Coupon zur Bearbeitung ausgewählt werden.

Es gibt ein Log:

```
[13-Aug-2024 09:08:27 Europe/Berlin] Request URI: /admin/index.php?cmd=coupon_admin&language=de&cmd=coupon_admin&page=1&cid=81, IP address: 2a02:8108:983f:e8c0::5d29, Language id 43
#0 /admin/coupon_admin.php(1161): zen_debug_error_handler()
#1 /admin/index.php(18): require('...')
--> PHP Warning: Attempt to read property "coupon_id" on null in /admin/coupon_admin.php on line 1161.

[13-Aug-2024 09:08:27 Europe/Berlin] Request URI: /admin/index.php?cmd=coupon_admin&language=de&cmd=coupon_admin&page=1&cid=81, IP address: 2a02:8108:983f:e8c0::5d29, Language id 43
#0 /admin/coupon_admin.php(1213): zen_debug_error_handler()
#1 /admin/index.php(18): require('...')
--> PHP Warning: Undefined variable $cInfo in /admin/coupon_admin.php on line 1213.
```

**Comment by webchills** [comment]
fixed with 9b50497b70b2f06162fcbce6c1ee684722e2014c
